name: 定时更新

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@master


    - name: run cmd
      run: |
        cp main main_tmp
        chmod +x main_tmp
        ./main_tmp cfg.json
        rm main_tmp

    - uses: actions/checkout@v2
    - name: Commit Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "46045921+hellowzsg@users.noreply.github.com"
        git config --global user.name "wakk"
        git add ./v2.txt
        git commit -m "Commit file"
        git push
