name: 更新节点

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@master


    - name: run cmd
      run: |
        cp main main_tmp
        chmod +x main_tmp
        ./main_tmp cfg.json
        rm main_tmp

    # - uses: actions/checkout@v2
    - name: Commit Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "46045921+hellowzsg@users.noreply.github.com"
        git config --global user.name "wakk"
        git status
        git add ./v2.txt
        git commit -m "Commit v2.txt"
        git push

    - uses: ryand56/r2-upload-action@latest
      name: put object cf R2
      with:
        r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
        r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
        r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        r2-bucket: ${{ secrets.R2_BUCKET }}
        source-dir: proxy   
